mod common;

use common::*;
use player_subtitles::{ass::line::*, *};
use std::fs;

const SIMPLE: &[u8] = br"[Script Info]
ScriptType: v4.00+
WrapStyle: 0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00:00,0:00:05:00,Default,,0,0,0,,It's simple subtitles
";

#[test]
fn iter() {
    let mut ass = AssLines::from_bytes(SIMPLE);
    assert_eq!(
        ass.next().unwrap(),
        AssLine::SectionMark(SectionMark::ScriptInfo)
    );
    assert!(matches!(
        ass.next().unwrap(),
        AssLine::ScriptInfo(ScriptInfo::ScriptType(_))
    ));
    assert!(matches!(
        ass.next().unwrap(),
        AssLine::ScriptInfo(ScriptInfo::WrapStyle(_))
    ));
    assert!(matches!(ass.next().unwrap(), AssLine::Blank));
    assert!(matches!(
        ass.next().unwrap(),
        AssLine::SectionMark(SectionMark::Events)
    ));
    assert!(matches!(ass.next().unwrap(), AssLine::EventFormat(_)));
    assert!(matches!(ass.next().unwrap(), AssLine::Event(_)));
}

const EXPECTED: &[u8] = concat!(
    "[Script Info]\n",
    "; Script generated by ",
    env!("CARGO_PKG_NAME"),
    " v",
    env!("CARGO_PKG_VERSION"),
    "\n",
    r"ScriptType: v4.00+
WrapStyle: 0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00:00,0:00:05:00,Default,,0,0,0,,It's simple subtitles
"
)
.as_bytes();

macro_rules! build_test_from_a_lines {
    ($fn:ident, $lines:ident, $src:expr, $dst:expr) => {
        #[test]
        fn $fn() {
            let dst = temp($dst);
            let src = $lines::open_file(data($src)).unwrap();
            let mut ass = AssLines::from(src);
            ass.write(&dst).unwrap();

            assert_eq!(fs::read(&dst).unwrap(), EXPECTED);
        }
    };
}

build_test_from_a_lines!(
    from_srt_lines,
    SrtLines,
    "srt.srt",
    "ass_from_srt_lines.ass"
);
build_test_from_a_lines!(
    from_vtt_lines,
    VttLines,
    "vtt.vtt",
    "ass_from_vtt_lines.ass"
);
